#line 2 "lexer.cpp"

#line 4 "lexer.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 143
#define YY_END_OF_BUFFER 144
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[452] =
    {   0,
        0,    0,  144,  142,    2,    1,   35,  142,   26,   29,
      142,   13,   14,   24,   22,   66,   23,   20,   25,  135,
      135,   16,   15,   38,   37,   39,   18,  132,  132,    9,
       11,   27,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  132,    5,   31,    7,   33,    2,   56,    0,  140,
        0,   44,    8,   60,   47,    0,  138,    0,   42,   64,
       40,   65,   41,   68,   21,    0,  136,    3,    4,   43,
      136,  134,  135,    0,  135,  135,    0,   19,   12,    6,
       10,   51,   58,   55,   59,   52,  132,    0,    0,   45,

      132,  132,  132,  132,  132,  132,  132,  132,  132,  132,
      132,   82,  132,  132,  132,  132,  132,  132,  132,  132,
      132,   95,  132,  132,  132,  132,  132,  132,  132,   63,
      132,  132,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,  132,  132,  132,  132,  132,   49,   62,
        0,  140,    0,    0,  138,    0,   67,   17,    0,  136,
      134,  134,    0,  137,  135,  135,  133,   53,   54,    0,
      141,    0,    0,  139,    0,   61,   69,  132,  132,  132,
      132,  132,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,  132,  132,  132,  132,   92,  132,  132,

      132,   97,  132,  132,  132,  101,   36,  132,  132,  132,
      132,  132,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,  132,  132,  120,  132,  132,  132,  132,
      132,  132,  132,  132,  132,   28,    0,  136,  134,  134,
      137,  133,  133,    0,  141,    0,    0,  139,    0,  132,
       70,  132,  132,   71,  132,   73,  132,   75,  132,  132,
      132,  132,  132,  132,  132,  132,   85,   86,  132,  132,
      132,  132,  132,  132,   94,  132,   98,  132,  132,  132,
      132,  132,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,  132,  132,  117,  132,  119,  132,  132,

      132,  132,  132,  128,  132,  132,  132,  132,  133,  133,
      132,  132,   32,   72,   74,   76,   34,   77,  132,  132,
      132,  132,  132,  132,  132,  132,   90,   91,  132,  132,
      132,  132,  132,  132,   50,  132,  132,  132,  132,  132,
      132,  109,  132,  132,  132,  132,  132,  132,  118,  132,
      132,  132,  124,  132,  126,  132,  132,  132,  131,  132,
       48,   30,  132,  132,  132,   81,   83,  132,  132,   88,
       89,   93,   96,  132,  132,   57,  132,  132,  132,  105,
      132,  132,  108,  110,  111,  112,  114,  115,  132,  132,
      122,  132,  132,  132,  132,  132,   46,  132,  132,   80,

      132,  132,   99,  132,  132,  103,  132,  132,  132,  132,
      132,  121,  132,  132,  127,  132,  130,  132,   79,  132,
       87,  132,  102,  132,  106,  132,  132,  116,  123,  125,
      129,  132,  132,  100,  104,  132,  132,   78,  132,  132,
      132,  132,  132,  113,   84,  132,  132,  132,  132,  107,
        0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   19,   19,   20,   21,   22,
       23,   24,   25,    1,   26,   26,   26,   26,   27,   28,
       29,   29,   29,   29,   29,   30,   29,   29,   29,   29,
       29,   29,   29,   29,   31,   29,   29,   32,   29,   29,
       33,   34,   35,   36,   37,    1,   38,   39,   40,   41,

       42,   43,   44,   45,   46,   29,   47,   48,   49,   50,
       51,   52,   53,   54,   55,   56,   57,   58,   59,   60,
       61,   62,   63,   64,   65,   66,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[67] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    2,    2,    2,    1,
        1,    1,    1,    1,    1,    2,    2,    2,    3,    3,
        3,    3,    1,    1,    1,    1,    3,    2,    2,    2,
        2,    2,    2,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[462] =
    {   0,
        0,    0,  587,  588,  584,  588,  562,   62,   45,   63,
       63,  588,  588,  561,   60,  588,   61,   62,   71,   83,
       72,   54,  588,   85,  560,   69,  588,    0,   98,  588,
      588,  559,   61,   66,   85,   77,   74,   91,  530,   45,
      529,  522,   99,   92,   94,  536,  107,  113,   71,  103,
      116,  526,  588,  104,  588,  588,  574,  588,  130,  588,
      154,  588,  588,  588,  588,  139,  588,  157,  588,  588,
      588,  588,  588,  564,  588,  559,  152,  588,  588,  588,
      159,  193,    0,  213,  141,  145,    0,  588,  588,  588,
      588,  550,  588,  588,  588,  549,    0,  179,  175,  588,

      530,  521,  513,  512,  516,  524,  141,  527,  526,  154,
      142,  506,  512,  506,  503,  162,  511,  507,  503,  510,
      499,    0,  173,  504,  497,  503,  492,  494,  507,  511,
      171,  508,  182,  495,  137,  195,  499,  495,  188,  158,
      491,  190,  496,  487,  191,  495,  493,  484,  588,  588,
      235,  238,  241,  239,  240,  248,  588,  588,  240,  588,
      222,  230,  244,  266,  588,  588,  240,  588,  588,  259,
      588,  284,  247,  588,  283,  500,    0,  485,  154,  487,
      496,  491,  492,  477,  475,  477,  210,  490,  485,  487,
      487,  482,  474,  229,  480,  466,  482,    0,  477,  467,

      471,    0,  472,  477,  472,    0,  476,  458,  469,  452,
      453,  460,  461,  456,  448,  450,  453,  460,  445,  443,
      443,  446,  442,  445,  453,    0,  452,  442,  446,  441,
      434,  448,  450,  449,  438,  448,  281,  285,  588,  588,
      588,  259,  262,  271,  290,  303,  293,  304,  317,  442,
        0,  433,  428,    0,  434,    0,  435,    0,  424,  430,
      421,  430,  418,  418,  425,  423,    0,    0,  425,  416,
      415,  426,  411,  416,    0,  415,    0,  425,  408,  420,
      423,  407,  421,  416,  411,  401,  399,  400,  397,  410,
      400,  404,  409,  408,  399,    0,  387,    0,  280,  395,

      400,  399,  385,    0,  385,  386,  397,  396,  588,  588,
      384,  395,    0,    0,    0,    0,    0,  398,  384,  385,
      390,  389,  384,  389,  372,  377,    0,    0,  385,  383,
      376,  371,  369,  365,    0,  364,  379,  378,  361,  374,
      365,    0,  373,  370,  372,  355,  365,  371,    0,  366,
      366,  368,    0,  355,    0,  366,  357,  365,    0,  348,
        0,    0,  360,  342,  342,    0,    0,  357,  350,    0,
        0,    0,    0,  353,  356,    0,  342,  350,  335,    0,
      348,  335,    0,    0,    0,  351,    0,    0,  331,  343,
        0,  336,  342,  335,  334,  325,    0,  342,  337,    0,

      341,  294,    0,  309,  294,    0,  305,  292,  293,  304,
      301,    0,  300,  300,    0,  298,    0,  284,    0,  296,
        0,  293,    0,  293,    0,  278,  293,    0,    0,    0,
        0,  273,  285,    0,    0,  280,  264,    0,  256,  251,
      212,  211,  179,    0,    0,  166,  124,   54,   43,    0,
      588,  351,  354,  356,  359,  362,   74,  365,  368,  371,
      374
    } ;

static yyconst flex_int16_t yy_def[462] =
    {   0,
      451,    1,  451,  451,  451,  451,  451,  452,  451,  451,
      453,  451,  451,  451,  451,  451,  451,  451,  451,  451,
       20,  451,  451,  451,  451,  451,  451,  454,  454,  451,
      451,  451,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  451,  451,  451,  451,  451,  451,  452,  451,
      455,  451,  451,  451,  451,  453,  451,  456,  451,  451,
      451,  451,  451,  451,  451,  451,  451,  451,  451,  451,
      451,  451,   21,  451,  451,  451,  457,  451,  451,  451,
      451,  451,  451,  451,  451,  451,  454,  458,  459,  451,

      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  451,  451,
      452,  452,  455,  453,  453,  456,  451,  451,  451,  451,
      451,  451,  451,  451,  451,  451,  457,  451,  451,  458,
      451,  460,  459,  451,  461,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,

      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  451,  451,  451,  451,
      451,  451,  451,  458,  458,  460,  459,  459,  461,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,

      454,  454,  454,  454,  454,  454,  454,  454,  451,  451,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,

      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
        0,  451,  451,  451,  451,  451,  451,  451,  451,  451,
      451
    } ;

static yyconst flex_int16_t yy_nxt[655] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   21,   22,
       23,   24,   25,   26,   27,   28,   28,   28,   28,   29,
       28,   28,   30,    4,   31,   32,   28,   33,   34,   35,
       36,   37,   38,   39,   28,   40,   28,   41,   42,   43,
       44,   45,   28,   46,   47,   48,   49,   50,   51,   52,
       28,   28,   53,   54,   55,   56,   60,   62,   63,   64,
       67,   70,   75,   88,   72,  167,   76,   89,   77,   77,
       77,   78,   71,   73,   74,   65,   79,  122,   83,   83,
       90,   95,   96,   80,  123,   61,   68,   81,  450,   82,

       82,   83,   98,  451,   91,   99,   92,   93,  449,   84,
      101,  104,   85,   86,   87,  102,  105,  103,  111,  106,
      142,  114,  107,  115,   84,  143,  149,  112,  117,  108,
       85,  451,  109,  116,   60,  110,  126,  113,  118,   86,
      127,  119,   87,  129,  120,  130,   67,  131,  144,  128,
      132,  134,  135,  145,  138,  146,   59,  139,  152,   66,
      147,  448,  136,   61,  155,  137,  140,  150,   77,   77,
       77,  165,   68,  141,  166,   77,   77,   77,  159,  160,
      217,  160,  174,  171,  188,  159,  160,  153,  160,  189,
      156,  252,  166,  159,  160,  182,  183,  165,  218,  160,

      159,  160,  186,  187,  253,  447,  160,   81,  175,   82,
       82,   83,  172,  194,  225,  446,  210,  195,  226,   84,
      201,  211,  161,  162,  163,  213,  163,  214,  202,  164,
      164,  164,  219,  223,   84,  228,  232,  215,  233,   60,
      161,  224,   60,   59,  229,  152,   67,   67,  220,  162,
       66,  237,  239,  237,  174,  155,  238,  238,  238,  240,
      164,  164,  164,  171,  261,  262,  445,  444,   61,  242,
      243,   61,   68,   68,  153,  171,  269,  240,  239,  270,
      175,  156,  164,  164,  164,  173,  170,  242,  245,  309,
      248,  310,  172,  241,  171,  241,  243,  238,  238,  238,

      174,  238,  238,  238,  172,  170,  443,  245,  241,  310,
      442,  174,  160,  241,  160,  309,  249,  246,  441,  173,
      350,  440,  439,  172,  248,  351,  175,  160,  438,  352,
      437,  436,  160,  435,  434,  433,  246,  175,  432,  431,
      430,  429,  428,  427,  426,  425,  424,  423,  422,  421,
      249,   59,   59,   59,   66,   66,   66,   97,   97,  151,
      151,  151,  154,  154,  154,  170,  170,  170,  173,  173,
      173,  244,  244,  244,  247,  247,  247,  420,  419,  418,
      417,  416,  415,  414,  413,  412,  411,  410,  409,  408,
      407,  406,  405,  404,  403,  402,  401,  400,  399,  398,

      397,  396,  395,  394,  393,  392,  391,  390,  389,  388,
      387,  386,  385,  384,  383,  382,  381,  380,  379,  378,
      377,  376,  375,  374,  373,  372,  371,  370,  369,  368,
      367,  366,  365,  364,  363,  362,  361,  360,  359,  358,
      357,  356,  355,  354,  353,  349,  348,  347,  346,  345,
      344,  343,  342,  341,  340,  339,  338,  337,  336,  335,
      334,  333,  332,  331,  330,  329,  328,  327,  326,  325,
      324,  323,  322,  321,  320,  319,  318,  317,  316,  315,
      314,  313,  312,  311,  308,  307,  306,  305,  304,  303,
      302,  301,  300,  299,  298,  297,  296,  295,  294,  293,

      292,  291,  290,  289,  288,  287,  286,  285,  284,  283,
      282,  281,  280,  279,  278,  277,  276,  275,  274,  273,
      272,  271,  268,  267,  266,  265,  264,  263,  260,  259,
      258,  257,  256,  255,  254,  251,  250,  236,  235,  234,
      231,  230,  227,  222,  221,  216,  212,  209,  208,  207,
      206,  205,  204,  203,  200,  199,  198,  197,  196,  193,
      192,  191,  190,  185,  184,  181,  180,  179,  178,  177,
      176,  169,  168,  158,  157,   57,  148,  133,  125,  124,
      121,  100,   94,   69,   58,   57,  451,    3,  451,  451,
      451,  451,  451,  451,  451,  451,  451,  451,  451,  451,

      451,  451,  451,  451,  451,  451,  451,  451,  451,  451,
      451,  451,  451,  451,  451,  451,  451,  451,  451,  451,
      451,  451,  451,  451,  451,  451,  451,  451,  451,  451,
      451,  451,  451,  451,  451,  451,  451,  451,  451,  451,
      451,  451,  451,  451,  451,  451,  451,  451,  451,  451,
      451,  451,  451,  451
    } ;

static yyconst flex_int16_t yy_chk[655] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    8,    9,    9,   10,
       11,   15,   18,   22,   17,  457,   18,   22,   18,   18,
       18,   19,   15,   17,   17,   10,   19,   40,   21,   21,
       24,   26,   26,   19,   40,    8,   11,   20,  449,   20,

       20,   20,   29,   21,   24,   29,   24,   24,  448,   20,
       33,   34,   20,   20,   20,   33,   34,   33,   36,   34,
       49,   37,   35,   37,   20,   49,   54,   36,   38,   35,
       20,   21,   35,   37,   59,   35,   43,   36,   38,   20,
       43,   38,   20,   44,   38,   44,   66,   45,   50,   43,
       45,   47,   47,   50,   48,   51,   61,   48,   61,   68,
       51,  447,   47,   59,   68,   47,   48,   54,   77,   77,
       77,   85,   66,   48,   86,   81,   81,   81,   77,   77,
      135,   77,   99,   98,  111,   81,   81,   61,   81,  111,
       68,  179,   86,   77,   77,  107,  107,   85,  135,   77,

       81,   81,  110,  110,  179,  446,   81,   82,   99,   82,
       82,   82,   98,  116,  140,  443,  131,  116,  140,   82,
      123,  131,   82,   82,   84,  133,   84,  133,  123,   84,
       84,   84,  136,  139,   82,  142,  145,  133,  145,  151,
       82,  139,  152,  153,  142,  153,  154,  155,  136,   82,
      156,  159,  161,  159,  173,  156,  159,  159,  159,  162,
      163,  163,  163,  170,  187,  187,  442,  441,  151,  167,
      167,  152,  154,  155,  153,  244,  194,  162,  161,  194,
      173,  156,  164,  164,  164,  175,  172,  167,  172,  242,
      175,  243,  170,  164,  245,  164,  167,  237,  237,  237,

      247,  238,  238,  238,  244,  246,  440,  246,  164,  243,
      439,  248,  238,  164,  238,  242,  175,  172,  437,  249,
      299,  436,  433,  245,  249,  299,  247,  238,  432,  299,
      427,  426,  238,  424,  422,  420,  246,  248,  418,  416,
      414,  413,  411,  410,  409,  408,  407,  405,  404,  402,
      249,  452,  452,  452,  453,  453,  453,  454,  454,  455,
      455,  455,  456,  456,  456,  458,  458,  458,  459,  459,
      459,  460,  460,  460,  461,  461,  461,  401,  399,  398,
      396,  395,  394,  393,  392,  390,  389,  386,  382,  381,
      379,  378,  377,  375,  374,  369,  368,  365,  364,  363,

      360,  358,  357,  356,  354,  352,  351,  350,  348,  347,
      346,  345,  344,  343,  341,  340,  339,  338,  337,  336,
      334,  333,  332,  331,  330,  329,  326,  325,  324,  323,
      322,  321,  320,  319,  318,  312,  311,  308,  307,  306,
      305,  303,  302,  301,  300,  297,  295,  294,  293,  292,
      291,  290,  289,  288,  287,  286,  285,  284,  283,  282,
      281,  280,  279,  278,  276,  274,  273,  272,  271,  270,
      269,  266,  265,  264,  263,  262,  261,  260,  259,  257,
      255,  253,  252,  250,  236,  235,  234,  233,  232,  231,
      230,  229,  228,  227,  225,  224,  223,  222,  221,  220,

      219,  218,  217,  216,  215,  214,  213,  212,  211,  210,
      209,  208,  207,  205,  204,  203,  201,  200,  199,  197,
      196,  195,  193,  192,  191,  190,  189,  188,  186,  185,
      184,  183,  182,  181,  180,  178,  176,  148,  147,  146,
      144,  143,  141,  138,  137,  134,  132,  130,  129,  128,
      127,  126,  125,  124,  121,  120,  119,  118,  117,  115,
      114,  113,  112,  109,  108,  106,  105,  104,  103,  102,
      101,   96,   92,   76,   74,   57,   52,   46,   42,   41,
       39,   32,   25,   14,    7,    5,    3,  451,  451,  451,
      451,  451,  451,  451,  451,  451,  451,  451,  451,  451,

      451,  451,  451,  451,  451,  451,  451,  451,  451,  451,
      451,  451,  451,  451,  451,  451,  451,  451,  451,  451,
      451,  451,  451,  451,  451,  451,  451,  451,  451,  451,
      451,  451,  451,  451,  451,  451,  451,  451,  451,  451,
      451,  451,  451,  451,  451,  451,  451,  451,  451,  451,
      451,  451,  451,  451
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
/*	$Id: lexer.l,v 1.2 1997/11/19 15:13:15 sandro Exp $	*/
/*
 * Copyright (c) 1997 Sandro Sigala <ssigala@globalnet.it>.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
/*
 * ISO C++ lexical analyzer.
 *
 * Based on the ISO C++ draft standard of December '96.
 */
#line 35 "lexer.l"
#include <io.h>
#include <ctype.h>
#include <stdio.h>

#include "parser.h"

int nextcolumnno = 1;

int columnno = nextcolumnno;

int lineno = 1;

#define YY_USER_ACTION \
	{\
		columnno = nextcolumnno;\
		nextcolumnno += yyleng;\
	}

extern "C" int yywrap(void);
static void skip_until_eol(void);
static void skip_comment(void);
static int check_identifier(const char * s);
#line 800 "lexer.cpp"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 66 "lexer.l"


#line 985 "lexer.cpp"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 452 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 588 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 68 "lexer.l"
{ ++lineno; columnno = nextcolumnno = 1; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 69 "lexer.l"
{ /* Ignore whitespace. */ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 71 "lexer.l"
{ skip_comment(); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 72 "lexer.l"
{ skip_until_eol(); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 74 "lexer.l"
{ return '{'; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 75 "lexer.l"
{ return '{'; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 76 "lexer.l"
{ return '}'; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 77 "lexer.l"
{ return '}'; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 78 "lexer.l"
{ return '['; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 79 "lexer.l"
{ return '['; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 80 "lexer.l"
{ return ']'; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 81 "lexer.l"
{ return ']'; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 82 "lexer.l"
{ return '('; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 83 "lexer.l"
{ return ')'; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 84 "lexer.l"
{ return ';'; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 85 "lexer.l"
{ return ':'; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 86 "lexer.l"
{ return ELLIPSIS; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 87 "lexer.l"
{ return '?'; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 88 "lexer.l"
{ return COLONCOLON; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 89 "lexer.l"
{ return '.'; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 90 "lexer.l"
{ return DOTSTAR; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 91 "lexer.l"
{ return '+'; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 92 "lexer.l"
{ return '-'; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 93 "lexer.l"
{ return '*'; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 94 "lexer.l"
{ return '/'; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 95 "lexer.l"
{ return '%'; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 96 "lexer.l"
{ return '^'; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 97 "lexer.l"
{ return '^'; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 98 "lexer.l"
{ return '&'; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 99 "lexer.l"
{ return '&'; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 100 "lexer.l"
{ return '|'; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 101 "lexer.l"
{ return '|'; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 102 "lexer.l"
{ return '~'; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 103 "lexer.l"
{ return '~'; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 104 "lexer.l"
{ return '!'; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 105 "lexer.l"
{ return '!'; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 106 "lexer.l"
{ return '='; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 107 "lexer.l"
{ return '<'; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 108 "lexer.l"
{ return '>'; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 109 "lexer.l"
{ return ADDEQ; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 110 "lexer.l"
{ return SUBEQ; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 111 "lexer.l"
{ return MULEQ; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 112 "lexer.l"
{ return DIVEQ; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 113 "lexer.l"
{ return MODEQ; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 114 "lexer.l"
{ return XOREQ; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 115 "lexer.l"
{ return XOREQ; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 116 "lexer.l"
{ return ANDEQ; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 117 "lexer.l"
{ return ANDEQ; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 118 "lexer.l"
{ return OREQ; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 119 "lexer.l"
{ return OREQ; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 120 "lexer.l"
{ return SL; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 121 "lexer.l"
{ return SR; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 122 "lexer.l"
{ return SLEQ; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 123 "lexer.l"
{ return SREQ; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 124 "lexer.l"
{ return EQ; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 125 "lexer.l"
{ return NOTEQ; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 126 "lexer.l"
{ return NOTEQ; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 127 "lexer.l"
{ return LTEQ; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 128 "lexer.l"
{ return GTEQ; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 129 "lexer.l"
{ return ANDAND; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 130 "lexer.l"
{ return ANDAND; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 131 "lexer.l"
{ return OROR; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 132 "lexer.l"
{ return OROR; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 133 "lexer.l"
{ return PLUSPLUS; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 134 "lexer.l"
{ return MINUSMINUS; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 135 "lexer.l"
{ return ','; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 136 "lexer.l"
{ return ARROWSTAR; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 137 "lexer.l"
{ return ARROW; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 139 "lexer.l"
{ return ASM; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 140 "lexer.l"
{ return AUTO; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 141 "lexer.l"
{ return BOOL; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 142 "lexer.l"
{ return BREAK; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 143 "lexer.l"
{ return CASE; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 144 "lexer.l"
{ return CATCH; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 145 "lexer.l"
{ return CHAR; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 146 "lexer.l"
{ return CLASS; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 147 "lexer.l"
{ return CONST; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 148 "lexer.l"
{ return CONST_CAST; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 149 "lexer.l"
{ return CONTINUE; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 150 "lexer.l"
{ return DEFAULT; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 151 "lexer.l"
{ return DELETE; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 152 "lexer.l"
{ return DO; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 153 "lexer.l"
{ return DOUBLE; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 154 "lexer.l"
{ return DYNAMIC_CAST; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 155 "lexer.l"
{ return ELSE; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 156 "lexer.l"
{ return ENUM; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 157 "lexer.l"
{ return EXPLICIT; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 158 "lexer.l"
{ return EXPORT; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 159 "lexer.l"
{ return EXTERN; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 160 "lexer.l"
{ return FALSE; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 161 "lexer.l"
{ return FLOAT; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 162 "lexer.l"
{ return FOR; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 163 "lexer.l"
{ return FRIEND; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 164 "lexer.l"
{ return GOTO; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 165 "lexer.l"
{ return IF; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 166 "lexer.l"
{ return INLINE; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 167 "lexer.l"
{ return INT; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 168 "lexer.l"
{ return LONG; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 169 "lexer.l"
{ return MUTABLE; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 170 "lexer.l"
{ return NAMESPACE; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 171 "lexer.l"
{ return NEW; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 172 "lexer.l"
{ return OPERATOR; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 173 "lexer.l"
{ return PRIVATE; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 174 "lexer.l"
{ return PROTECTED; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 175 "lexer.l"
{ return PUBLIC; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 176 "lexer.l"
{ return REGISTER; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 177 "lexer.l"
{ return REINTERPRET_CAST; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 178 "lexer.l"
{ return RETURN; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 179 "lexer.l"
{ return SHORT; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 180 "lexer.l"
{ return SIGNED; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 181 "lexer.l"
{ return SIZEOF; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 182 "lexer.l"
{ return STATIC; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 183 "lexer.l"
{ return STATIC_CAST; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 184 "lexer.l"
{ return STRUCT; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 185 "lexer.l"
{ return SWITCH; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 186 "lexer.l"
{ return TEMPLATE; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 187 "lexer.l"
{ return THIS; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 188 "lexer.l"
{ return THROW; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 189 "lexer.l"
{ return TRUE; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 190 "lexer.l"
{ return TRY; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 191 "lexer.l"
{ return TYPEDEF; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 192 "lexer.l"
{ return TYPEID; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 193 "lexer.l"
{ return TYPENAME; }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 194 "lexer.l"
{ return UNION; }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 195 "lexer.l"
{ return UNSIGNED; }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 196 "lexer.l"
{ return USING; }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 197 "lexer.l"
{ return VIRTUAL; }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 198 "lexer.l"
{ return VOID; }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 199 "lexer.l"
{ return VOLATILE; }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 200 "lexer.l"
{ return WCHAR_T; }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 201 "lexer.l"
{ return WHILE; }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 203 "lexer.l"
{ return check_identifier(yytext); }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 205 "lexer.l"
{ return INTEGER; }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 206 "lexer.l"
{ return INTEGER; }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 207 "lexer.l"
{ return INTEGER; }
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 209 "lexer.l"
{ return FLOATING; }
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 210 "lexer.l"
{ return FLOATING; }
	YY_BREAK
case 138:
/* rule 138 can match eol */
YY_RULE_SETUP
#line 212 "lexer.l"
{ return CHARACTER; }
	YY_BREAK
case 139:
/* rule 139 can match eol */
YY_RULE_SETUP
#line 213 "lexer.l"
{ return CHARACTER; }
	YY_BREAK
case 140:
/* rule 140 can match eol */
YY_RULE_SETUP
#line 215 "lexer.l"
{ return STRING; }
	YY_BREAK
case 141:
/* rule 141 can match eol */
YY_RULE_SETUP
#line 216 "lexer.l"
{ return STRING; }
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 218 "lexer.l"
{ fprintf(stderr, "%d: unexpected character `%c'\n", lineno, yytext[0]); }
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 220 "lexer.l"
ECHO;
	YY_BREAK
#line 1788 "lexer.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 452 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 452 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 451);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 220 "lexer.l"



int
yywrap(void)
{
	return 1;
}

/*
 * We use this routine instead a lex pattern because we don't need
 * to save the matched comment in the `yytext' buffer.
 */
static void
skip_comment(void)
{
	int c1, c2;

	c1 = yyinput();
	c2 = yyinput();

	while (c2 != EOF && !(c1 == '*' && c2 == '/')) {
		if (c1 == '\n')
			++lineno;
		c1 = c2;
		c2 = yyinput();
	}
}

/*
 * See the previous comment for an explanation.
 */
static void
skip_until_eol(void)
{
	int c;

	while ((c = yyinput()) != EOF && c != '\n')
		;
	++lineno;
}

static int
check_identifier(const char * s)
{
	/*
	 * This function should check if `s' is a typedef name or a class
	 * name, or a enum name, ... etc. or an identifier.
	 */

	switch (s[0]) {
	case 'D': return TYPEDEF_NAME;
	case 'N': return NAMESPACE_NAME;
	case 'C': return CLASS_NAME;
	case 'E': return ENUM_NAME;
	case 'T': return TEMPLATE_NAME;
	}

	return IDENTIFIER;
}

